Query multi tables
michaelamponsah/vet-clinic pull request #3
Opened 2023-02-23 20:09 UTC by michaelamponsah

## Hello ☺️

### In this PR, the following requirements have been completed:

- [x] Created a table named owners with the following columns:
        id: integer (set it as autoincremented PRIMARY KEY)
        full_name: string
        age: integer  

- [x]  Created a table named species with the following columns:
        id: integer (set it as autoincremented PRIMARY KEY)
        name: string

- [x]  Modified animals table:
        Made sure that id is set as autoincremented PRIMARY KEY
        Removed column species
        Added column species_id which is a foreign key referencing species table
        Added column owner_id which is a foreign key referencing the ` owners table`

- [x] Executed all queries

> Below are screenshots demonstrating completed tasks. 

![Capture](https://user-images.githubusercontent.com/42746317/221018654-745ba139-8fbc-48f5-b4e7-d17927d6a6cd.PNG)

![2](https://user-images.githubusercontent.com/42746317/221018670-4a573bdc-bd54-441d-85c4-8026c65b1170.PNG)

![3](https://user-images.githubusercontent.com/42746317/221018692-1d956637-0123-4075-82e4-5a449324fdb2.PNG)

2023-02-23 20:55 UTC, Kamba56 requested changes
Hi @michaelamponsah, 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great use of Github workflow!👏👏👏
- [x] All linters passed
- [ ] Great job adding new tables and updating table entries

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 20:55 UTC, Kamba56 commented on data.sql
>  INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES ('Boarmon', '7/06/2005', 7, true,  20.4);
- [ ] Kindly edit all sections of your readme file and customize it to this project. Thsi will make your work more professional.
![image](https://user-images.githubusercontent.com/94551484/221022450-073fd20d-a755-4fe1-9d8e-b72ca427f9bb.png)
![image](https://user-images.githubusercontent.com/94551484/221022605-a3f8ce14-4936-4024-8f1e-0c1a5e65955a.png)
![image](https://user-images.githubusercontent.com/94551484/221022679-e55b5d4c-b965-4e03-bf8f-5f1a44c00341.png)
![image](https://user-images.githubusercontent.com/94551484/221022765-bded6085-a7db-45a5-b447-069cfa538740.png)

- [ ] Kindly fix the MIT license link in your readme file. The link should lead to the MIT license file in your repo.

2023-02-23 20:55 UTC, Kamba56 commented on queries.sql
> +SELECT species.name AS species, COUNT(animals.species_id) AS num FROM species  JOIN animals ON animals.species_id = species.id GROUP BY animals.species_id, species.name;
- [ ] All animals whose names end with `mon` are digimons. There are only 6 animals that end with `mon`. But from your screenshots, I see these returns 7, kindly look into that, please.

2023-02-23 20:55 UTC, Kamba56 commented on queries.sql
> +SELECT  owners.fullname AS owner_name, MAX(animals.owner_id) AS owner_id FROM animals JOIN owners ON animals.owner_id = owners.id WHERE animals.owner_id = owners.id GROUP BY owners.fullname, animals.
- [ ] Melody pond is the only owner that has 3 animals, so Melody should be returned as the person with the most animals, but that is not so in your screenshot, kindly fix the query please.

2023-02-23 20:55 UTC, Kamba56 commented on queries.sql
> +
- [ ] Please list the animal's name that belongs to Jennifer Owrwell instead of counting the animals.

2023-02-24 00:35 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @michaelamponsah     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 00:44 UTC, merged